apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image }}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: c8n-registry-secret
      resources:
        requests:
          memory: "128Mi"  # Minimum de mémoire allouée
          cpu: "100m"      # Minimum de CPU alloué
        limits:
          memory: "128Mi"  # Limite de mémoire allouée
          cpu: "100m"      # Limite de CPU allouée