apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: {{ .Release.Name }}-httpscaledobject
  namespace: default
spec:
  hosts:
    - {{ .Values.host }}
  scaleTargetRef:
    deployment: {{ .Release.Name }}-deployment
    kind: Deployment
    apiVersion: apps/v1
    service: {{ .Release.Name }}-service
    port: 80
  replicas:
    min: 0
    max: 5
  targetPendingRequests: 1
  cooldownPeriod: 300 # 5 minutes (valeur par default, mais ne semble pas être modifiable)  
  #scalingMetric:
  #  requestRate:
  #      granularity: 1s
  #      targetValue: 5
  #      window: 1m