apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  annotations:
    test: 123
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http