apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "80"
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http